instances:
  - sal_index: 1
    models:
      - model_class: RPiModel
        # COMCAM temperature sensor readout box
        config:
          host: comcam-ess01.cp.lsst.org
          devices:
          - name: CamHex_CCW-ESS01
            channels: 8
            device_type: FTDI
            ftdi_id: AK071D5X
            sensor_type: Temperature
            location: Motor 1 temp,Motor 2 temp,Strut 7 temp,Strut 8 temp,Strut 9 temp,Strut 10 temp,Strut 11 temp,Strut 12 temp
  - sal_index: 101
    models:
      - model_class: RPiModel
        # MTDome ESS01 humidity sensors.
        config:
          host: mtdome-rpi01.cp.lsst.org
          devices:
          - name: MTDome-ESS01
            device_type: Serial
            serial_port: serial_ch_2
            sensor_type: HX85A
            location: MTDome-ESS01
  - sal_index: 102
    models:
      - model_class: RPiModel
        # MTDome ESS02 humidity sensors.
        config:
          host: mtdome-rpi02.cp.lsst.org
          devices:
          - name: MTDome-ESS02
            device_type: Serial
            serial_port: serial_ch_2
            sensor_type: HX85A
            location: MTDome-ESS02
  - sal_index: 103
    models:
      - model_class: RPiModel
        # Configuration for the MTDome ESS03 humidity sensors.
        config:
          host: mtdome-rpi03.cp.lsst.org
          devices:
          - name: MTDome-ESS03
            device_type: Serial
            serial_port: serial_ch_2
            sensor_type: HX85A
            location: MTDome-ESS03
  - sal_index: 201
    models:
      - model_class: RPiModel
        # AuxTel temperature sensor readout box
        config:
          host: auxtel-ess01.cp.lsst.org
          devices:
          - name: AuxTel-ESS01
            channels: 4
            device_type: FTDI
            ftdi_id: AL05OBVR
            sensor_type: Temperature
            location: Unused,Air,Truss,M2
          - name: AuxTel-ESS02
            device_type: Serial
            serial_port: serial_ch_2
            sensor_type: HX85BA
            location: AzAxis
