instances:
  - sal_index: 1
    models:
      - model_class: RPiModel
        # COMCAM temperature sensor readout box
        config:
          host: comcam-ess01.cp.lsst.org
          devices:
          - name: CamHex_CCW-ESS01
            channels: 8
            device_type: FTDI
            ftdi_id: AK071D5X
            sensor_type: Temperature
            location: >-
              MT rotator motor 1,
              MT rotator motor 2,
              MT camera hexapod strut 7,
              MT camera hexapod strut 8,
              MT camera hexapod strut 9,
              MT camera hexapod strut 10,
              MT camera hexapod strut 11,
              MT camera hexapod strut 12
  - sal_index: 101
    models:
      - model_class: RPiModel
        # MTDome ESS01 humidity sensors.
        config:
          host: mtdome-rpi01.cp.lsst.org
          devices:
          - name: MTDome-ESS01
            device_type: Serial
            serial_port: serial_ch_2
            sensor_type: HX85A
            location: MT dome air handling unit 1
  - sal_index: 102
    models:
      - model_class: RPiModel
        # MTDome ESS02 humidity sensors.
        config:
          host: mtdome-rpi02.cp.lsst.org
          devices:
          - name: MTDome-ESS02
            device_type: Serial
            serial_port: serial_ch_2
            sensor_type: HX85A
            # TODO: is this sensor inside or outside?
            location: MT dome wall at 7th floor
  - sal_index: 103
    models:
      - model_class: RPiModel
        # Configuration for the MTDome ESS03 humidity sensors.
        config:
          host: mtdome-rpi03.cp.lsst.org
          devices:
          - name: MTDome-ESS03
            device_type: Serial
            serial_port: serial_ch_2
            sensor_type: HX85A
            location: MT dome inside at 8th floor
  - sal_index: 201
    models:
      - model_class: RPiModel
        # AuxTel temperature sensor readout box
        config:
          host: auxtel-ess01.cp.lsst.org
          devices:
          - name: AuxTel-ESS01
            channels: 4
            device_type: FTDI
            ftdi_id: AL05OBVR
            sensor_type: Temperature
            location: unused, AT air, AT truss, AT M2
          - name: AuxTel-ESS02
            device_type: Serial
            serial_port: serial_ch_2
            sensor_type: HX85BA
            location: AT azimuth axis
